"""changes backend

Revision ID: 8bf42fa0d108
Revises: 96bc953d7cf6
Create Date: 2026-10-08 07:44:09.611710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bf42fa0d108'
down_revision = '96bc953d7cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pedido_id', sa.Integer(), nullable=False))
        batch_op.alter_column('factura_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'pedidos', ['pedido_id'], ['id'])

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo_cancelacion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('motivo_cancelacion')

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('factura_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('pedido_id')

    # ### end Alembic commands ###
